// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace ControleGastosResidenciais.Models;

[Table("CATEGORIAS")]
public partial class Categoria
{
    [Key]
    [Column("CAId")]
    public int Caid { get; set; }

    [Required]
    [Column("CADescricao")]
    [StringLength(400)]
    [Unicode(false)]
    public string Cadescricao { get; set; }

    [Required]
    [Column("CAFinalidade")]
    [StringLength(20)]
    [Unicode(false)]
    public string Cafinalidade { get; set; }

    //[InverseProperty("Trcategoria")]
    [JsonIgnore]
    public virtual ICollection<Transacao> Transacoes { get; set; } = new List<Transacao>();
}