// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ControleGastosResidenciais.Models;

public partial class ControleGastosContext : DbContext
{
    public ControleGastosContext()
    {
    }

    public ControleGastosContext(DbContextOptions<ControleGastosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categoria> Categorias { get; set; }

    public virtual DbSet<Pessoa> Pessoas { get; set; }

    public virtual DbSet<Transacao> Transacoes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Transacao>(entity =>
        {
            entity.HasOne(d => d.Trcategoria).WithMany(p => p.Transacoes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TRANSACOES_CATEGORIAS");

            entity.HasOne(d => d.Trpessoa).WithMany(p => p.Transacoes)
                .HasConstraintName("FK_TRANSACOES_PESSOAS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}