// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace ControleGastosResidenciais.Models;

[Table("PESSOAS")]
public partial class Pessoa
{
    [Key]
    [Column("PEId")]
    public int Peid { get; set; }

    [Required]
    [Column("PENome")]
    [StringLength(200)]
    [Unicode(false)]
    public string Penome { get; set; }

    [Column("PEIdade")]
    public int Peidade { get; set; }
    [JsonIgnore]
    public virtual ICollection<Transacao> Transacoes { get; set; } = new List<Transacao>();
}