// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace ControleGastosResidenciais.Models;

[Table("TRANSACOES")]
public partial class Transacao
{
    [Key]
    [Column("TRId")]
    public int Trid { get; set; }

    [Required]
    [Column("TRDescricao")]
    [StringLength(400)]
    [Unicode(false)]
    public string Trdescricao { get; set; }

    [Column("TRValor", TypeName = "decimal(10, 2)")]
    public decimal Trvalor { get; set; }

    [Required]
    [Column("TRTipo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Trtipo { get; set; }

    [Column("TRPessoaId")]
    public int TrpessoaId { get; set; }

    [Column("TRCategoriaId")]
    public int TrcategoriaId { get; set; }
    public DateTime Trdata { get; set; }

    [ForeignKey("TrcategoriaId")]
    public virtual Categoria Trcategoria { get; set; }

    [ForeignKey("TrpessoaId")]
    public virtual Pessoa Trpessoa { get; set; }
}